Repository apollographql/apollo-federation-subgraph-compatibility, pull requests merged in 2022-10, with the labels that each got.

#243 rename Hosted Subgraphs to Other Solutions
  README.md
  implementations/_template_hosted_/metadata.yaml
  implementations/appsync/metadata.yaml
  implementations/stepzen/metadata.yaml
Labels: type: documentation

#245 update dgs example with latest deps
  implementations/dgs/pom.xml
Labels: type: dependencies

#244 update federation-jvm example with latest deps
  implementations/federation-jvm/pom.xml
Labels: type: dependencies

#246 update apollo-server implementation to AS4
  implementations/apollo-server/index.js
  implementations/apollo-server/package-lock.json
  implementations/apollo-server/package.json
  package-lock.json
  subgraphs/inventory/index.js
  subgraphs/inventory/package-lock.json
  subgraphs/inventory/package.json
  subgraphs/users/index.js
  subgraphs/users/package-lock.json
  subgraphs/users/package.json
Labels: type: dependencies

#254 Update express-graphql implementation with latest Fed 2 tests
  implementations/express-graphql/package-lock.json
  implementations/express-graphql/package.json
  implementations/express-graphql/products.graphql
  implementations/express-graphql/src/index.ts
Labels: language: javascript, type: test
